blog/urls.py
from django.urls import path
from blog import views


app_name='blog'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog-list'),
    path('add/', views.BlogCreateView.as_view(), name='blog-add'),
    path('<int:pk>/detail', views.BlogDetailView.as_view(), name='blog-detail'),
    path('<int:pk>/update', views.BlogUpdateView.as_view(), name='blog-update'),
    path('<int:pk>/delete', views.BlogDeleteView.as_view(), name='blog-delete'),
]

comment/urls.py
from django.urls import path
from comment import views

app_name='comment'

urlpatterns = [
    path('', views.CommentListView.as_view(), name='comment-list'),
    path('add/', views.CommentCreateView.as_view(), name='comment-add'),
    path('<int:pk>/detail', views.CommentDetailView.as_view(), name='comment-detail'),
    path('<int:pk>/update', views.CommentUpdateView.as_view(), name='comment-update'),
    path('<int:pk>/delete', views.CommentDeleteView.as_view(), name='comment-delete'),
]

home/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from home import views

app_name='home'
urlpatterns = [
    path('', views.index, name='main'),
    path('about/', views.about, name='about'),
]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto_final_bidetti/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('comment/', include('comment.urls')),
    path('blog/', include('blog.urls')),
]

user/urls.py
from django.urls import path
from user import views

app_name='user'

urlpatterns = [
    path('login', views.login_request, name='user-login'),
    path('logout', views.logout_request, name='user-logout'),
    path('register', views.register, name='user-register'),
    path('register/update', views.user_update, name='user-update'),
    path('avatar/load', views.avatar_load, name='avatar-load'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.db.models import Q

#from user.models import Avatar


def index(request):
    return render(request, "home/main.html")

def about(request):
    return render(request, "home/about.html")

#def get_avatar_url_ctx(request):
#    avatars = Avatar.objects.filter(user=request.user.id)
#    if avatars.exists():
#        return {"url": avatars[0].image.url}
#    return {}

home/templates/home/about.html
{% extends "home/index.html" %}
{% load static %}
{% block content %}

<h2 class="bg-dark"> About </h2>
<div class="text-center bg-dark text-white">
    <a> Developer: Bidetti Torres Franco, is a student of electronic engineering and python. This project consists of a web page that simulates being a blog.  </a>
</div>

{% endblock %}

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
    <head>

        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
        <!-- Awesome fonts -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-dark static-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home:main' %}">Home</a>
                <a class="navbar-brand" href="{% url 'blog:blog-list' %}">Blogs</a>
                <a class="navbar-brand" href="{% url 'comment:comment-list' %}">Comments</a>
                {% if user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'user:user-update' %}">User</a>
                <a class="btn btn-primary" href="{% url 'user:user-logout' %}">Logout</a>
                {% else %}
                <a class="btn btn-primary" href="{% url 'user:user-login' %}">Login</a>
                {% endif %}
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5">Welcome to our blog <br> The Blog of the community</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <div class="bg-dark text-white text-center">
            {% block content %}

            {% endblock %}
        </div>
        
        <!-- Footer-->
        <footer class="footer bg-dark">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="{% url 'home:about' %}">About</a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2022. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>

        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

home/templates/home/main.html
{% extends "home/index.html" %}
{% load static %}
{% block content %}

<h2 class="bg-dark"> HOME </h2>
<div class="text-lg-start bg-dark text-white">
    <ul>
        <!--Mostrar los datos del home(entradas a blogs que esten en la bd)--->
    </ul>
</div>

{% endblock %}