blog/urls.py
from django.urls import path
from blog import views


app_name='blog'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog-list'),
    path('add/', views.BlogCreateView.as_view(), name='blog-add'),
    path('<int:pk>/detail', views.BlogDetailView.as_view(), name='blog-detail'),
    path('<int:pk>/update', views.BlogUpdateView.as_view(), name='blog-update'),
    path('<int:pk>/delete', views.BlogDeleteView.as_view(), name='blog-delete'),
]

comment/urls.py
from django.urls import path
from comment import views

app_name='comment'

urlpatterns = [
    path('', views.CommentListView.as_view(), name='comment-list'),
    path('add/', views.CommentCreateView.as_view(), name='comment-add'),
    path('<int:pk>/detail', views.CommentDetailView.as_view(), name='comment-detail'),
    path('<int:pk>/update', views.CommentUpdateView.as_view(), name='comment-update'),
    path('<int:pk>/delete', views.CommentDeleteView.as_view(), name='comment-delete'),
]

proyecto_final_bidetti/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('comment/', include('comment.urls')),
    path('blog/', include('blog.urls')),
]

comment/models.py
from django.db import models


class Comment(models.Model): 
    date = models.DateField()
    blog_title = models.CharField(max_length=50)
    comments = models.CharField(max_length=500)

    def __str__(self):
        return f'   {self.blog_title}   '

comment/views.py
from django.shortcuts import render
from comment.models import Comment
from django.views.generic.detail import DetailView
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


class CommentListView(ListView):
    model = Comment
    template_name = "comment/comment_list.html"

class CommentDetailView(DetailView):
    model = Comment
    template_name = "comment/comment_detail.html"
    fields = ['date', 'blog_title', 'comments']

class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    success_url = reverse_lazy('comment:comment-list')
    fields = ['date', 'blog_title', 'comments']

class CommentUpdateView(LoginRequiredMixin, UpdateView):
    model = Comment
    success_url = reverse_lazy('comment:comment-list')
    fields = ['date', 'blog_title', 'comments']

class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    success_url = reverse_lazy('comment:comment-list')

comment/templates/comment/comment_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}
{% block content %}

<h2>Delete comment</h2>
<hr></hr>

<p>Are you sure you want to delete the comment?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn2 btn-warning" type="submit" value="Yes, delete.">
    <a class="btn2 btn-primary" href="{% url 'comment:comment-list' %}" >Cancel</a>
</form>

{% endblock %}

comment/templates/comment/comment_detail.html
{% extends "home/index.html" %}
{% load static %}
{% block content %}

<h2>{{ comment.blog_title }}</h2>
<hr></hr>
<p><h5>{{ comment.date }}</h5></p>
<p><textarea readonly rows="7" cols="90" >{{ comment.comments }}</textarea></p>
<p><a class="btn2 btn-primary" href="{% url 'comment:comment-list' %}">Go back</a></p>

{% endblock %}

comment/templates/comment/comment_form.html
{% extends "home/index.html" %}
{% load static %}
{% block content %}

<h2> Create your Comment </h2>
<div class="text-lg-start bg-dark text-white">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        {{ form.as_p }}

        <input type="submit" class="btn btn-primary" value="Create Comment"/>
    </form>
</div>

{% endblock %}

comment/templates/comment/comment_list.html
{% extends "home/index.html" %}
{% load static %}
{% block content %}

<h2>Comments</h2>
{% if user.is_authenticated %}
<a class="card_custom" href="{% url 'comment:comment-add' %}">Create new comment</a>
{% endif %}
<hr></hr>
<ul>
    <div class="text-lg-start">
    {% for comment in comment_list %}
    <li>
        {{comment}}
        (
            <a href="{% url 'comment:comment-detail' comment.id %}">
                <i class="fa fa-eye" style="color: rgb(0, 0, 255);"> </i>
            </a>
        {% if user.is_authenticated %}
        |
        <a href="{% url 'comment:comment-update' comment.id %}">
            <i class="fa fa-pencil" style="color: rgb(0, 0, 190);"> </i>
        </a>
        |
        <a href="{% url 'comment:comment-delete' comment.id %}">
            <i class="fa fa-trash" style="color: rgb(0, 0, 100);"> </i>
        </a>
        {% endif %}
        )
    </li>
    {% endfor %}
    </div>
</ul>

{% endblock %}