blog/urls.py
from django.urls import path
from blog import views


app_name='blog'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog-list'),
    path('add/', views.BlogCreateView.as_view(), name='blog-add'),
    path('<int:pk>/detail', views.BlogDetailView.as_view(), name='blog-detail'),
    path('<int:pk>/update', views.BlogUpdateView.as_view(), name='blog-update'),
    path('<int:pk>/delete', views.BlogDeleteView.as_view(), name='blog-delete'),
]

proyecto_final_bidetti/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('comment/', include('comment.urls')),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models


class Blog(models.Model):
    date = models.DateField()
    autor = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=50)
    body = models.CharField(max_length=500)
    photo = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return f'   {self.title}   '

blog/views.py
from django.shortcuts import render
from blog.models import Blog
from django.views.generic.detail import DetailView
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


class BlogListView(ListView):
    model = Blog
    template_name = "blog/blog_list.html"

class BlogDetailView(DetailView):
    model = Blog
    template_name = "blog/blog_detail.html"
    fields = ['title', 'subtitle', 'date', 'autor', 'body', 'photo']

class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    success_url = reverse_lazy('blog:blog-list')
    fields = ['title', 'subtitle', 'date', 'autor', 'body', 'photo']

class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    success_url = reverse_lazy('blog:blog-list')
    fields = ['title', 'subtitle', 'date', 'autor', 'body', 'photo']

class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog-list')

blog/templates/blog/blog_confirm_delete.html
{% extends "home/index.html" %}
{% load static %}
{% block content %}

<h2>Delete blog</h2>
<hr></hr>

<p>Are you sure you want to delete the blog? {{ blog.name }}</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn2 btn-warning" type="submit" value="Yes, delete.">
    <a class="btn2 btn-primary" href="{% url 'blog:blog-list' %}" >Cancel</a>
</form>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "home/index.html" %}
{% load static %}
{% block content %}

<h2>{{ blog.title }}</h2>
<hr></hr>
<p><h4>{{ blog.subtitle }}</h4></p>
<p><h5>{{ blog.date }}, {{blog.autor}}</h5></p>
<p><textarea readonly rows="7" cols="90" >{{ blog.body }}</textarea></p>
{% if blog.photo %}
    <img src="{{ blog.photo.url }}">
{% endif %}
<img height="160px" src="{{blog.photo}}" alt="">
<p><a class="btn2 btn-primary" href="{% url 'blog:blog-list' %}">Go back</a></p>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends "home/index.html" %}
{% load static %}
{% block content %}

<h2> Create your Blog </h2>
<div class="text-lg-start bg-dark text-white">
    <form action="" method="POST">
        {% csrf_token %}
        
        {{ blog_form.as_p }}

        <input type="submit" class="btn btn-primary" value="Create Blog"/>
    </form>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends "home/index.html" %}
{% load static %}
{% block content %}

<h2>Blogs</h2>
{% if user.is_authenticated %}
<a class="card_custom" href="{% url 'blog:blog-add' %}">Create new blog</a>
{% endif %}
<hr></hr>
<ul>
    <div class="text-lg-start">
    {% for blog in blog_list %}
    <li>
        {{blog}}
        (
            <a href="{% url 'blog:blog-detail' blog.id %}">
                <i class="fa fa-eye" style="color: rgb(0, 0, 190);"> </i>
            </a>
        {% if user.is_authenticated %}
        |
        <a href="{% url 'blog:blog-update' blog.id %}">
            <i class="fa fa-pencil" style="color: rgb(0, 0, 190);"> </i>
        </a>
        |
        <a href="{% url 'blog:blog-delete' blog.id %}">
            <i class="fa fa-trash" style="color: rgb(0, 0, 190);"> </i>
        </a>
        {% endif %}
        )
    </li>
    {% endfor %}
    </div>
</ul>

{% endblock %}